### ISSUE TITLE
Unable to run aws/foundational_security policy

### ISSUE THREAD

**Issue by gs5741** [cloudquery-policies/aws#109]
### Describe the bug

Hi team,

I am trying to run foundational security policy on my AWS account for scanning, but I Keep getting this error which seems to suggest , the SQL isn't correct at -> https://github.com/cloudquery-policies/aws/blob/main/queries/kms/inline_policy_blocked_kms_actions.sql

### Expected Behavior

I should be getting the proper formatted output for aws/foundational_security checks

### Steps to Reproduce

On a cloudquery instance execute following command

cloudquery policy run aws//foundational_security

### Provider and CloudQuery version

Version: 0.20.4 Commit: 6a126a673e69afe34e352c03c2e5beb1578687d1

**Comment by irmatov** [comment]
Works for me. @gs5741 Can you provide the exact error that you're getting, please?

**Comment by yevgenypats** [comment]
@gs5741 Thx for reporting this! Can you please share the PostgreSQL version, this will help us try and reproduce it.

**Comment by gs5741** [comment]
Thanks for your response. Here it is 
cloudquery policy run aws//foundational_security
Initializing CloudQuery Providers...

✓ cq-provider-aws@v0.10.5 verified    3s  100 %

Finished provider initialization...

Starting policies run...

✓ policy "aws" -  evaluating -     2s   Finished Checks: 123/123

❌ Failed to run policies: foundational_security/kms/KMS.2: ERROR: cannot extract elements from an object (SQLSTATE 22023).

foundational_security/kms/KMS.2: ERROR: cannot extract elements from an object (SQLSTATE 22023)

**Comment by gs5741** [comment]
Here's the postgres version:

PostgreSQL 12.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit

**Comment by bbernays** [comment]
@gs5741 - Are you running your database locally or in a place you can access it? If you are, could you run the query you linked to directly against the db and let us know if there are any other errors or details?

**Comment by gs5741** [comment]
@bbernays , I am running it locally. I executed it already and get the same error :

ERROR:  cannot extract elements from an object
SQL state: 22023

**Comment by gs5741** [comment]
Great. The IAM Users: SQL fails with the exact same message :
ERROR:  cannot extract elements from an object
SQL state: 22023

There's only 1 row in aws_iam_user_policies with the policy_document as :
{
  "Version": "2012-10-17",
  "Statement": {
    "Action": "sts:AssumeRole",
    "Effect": "Allow",
    "Resource": "*"
  }
}

**Comment by bbernays** [comment]
Thank you so much for sending this to us! We did not know that was a valid policy document! We will add support for it and ping you when we release it (should be very soon)!

**Comment by gs5741** [comment]
Awesome ! Thanks for such a quick response. I look forward to the change

**Comment by bbernays** [comment]
@gs5741 - We have released a new version with a fix for the KMS control that you were running into issues with. Let us know if you have any other issues!

**Comment by gs5741** [comment]
Awesome. I just tested it and its working as expected. Thanks again !
