### ISSUE TITLE
Implement Standardized Linting

### ISSUE THREAD

**Issue by bbernays** [cloudquery-policies/aws#57]
Find, test and implement an SQL linter in our Github Actions in order to enforce a consistent feel across all of our queries

**Comment by roneli** [comment]
https://github.com/sqlfluff/sqlfluff

**Comment by bbernays** [comment]
They have an entire repo devoted to running sqlfluff on Github Actions: https://github.com/sqlfluff/sqlfluff-github-actions

I am down to standardize around their rule set for postgres:
```
sqlfluff fix . --dialect postgres
```

**Comment by disq** [comment]
Also https://online.sqlfluff.com/

**Comment by yevgenypats** [comment]
Done https://github.com/cloudquery-policies/aws/blob/main/.github/workflows/lint.yml
