### ISSUE TITLE
Change the about to point to the right 'hub' link

### ISSUE THREAD

**Issue by LuD1161** [cloudquery-policies/aws#81]
On the [repo main page](https://github.com/cloudquery-policies/aws), in about section the link to `hub` is incorrect.
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/17861054/147340409-2e90b301-87c2-4be6-a7ba-17bc5370ec00.png">

It should be [https://hub.cloudquery.io/](https://hub.cloudquery.io/)

**Comment by yevgenypats** [comment]
Thanks! Fixed.
