### ISSUE TITLE
APIGateway docs missing for foundational security

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery-policies/aws#95]
### Describe the bug

https://github.com/cloudquery-policies/aws/runs/4827299650?check_suite_focus=true

### Expected Behavior

NA

### Steps to Reproduce

NA

### Provider and CloudQuery version

0.19.1

**Comment by yevgenypats** [comment]
Found the issue. some of the docs are lower case and some are upper case. It's a small one but worth having some convention (I'd go for lowercase)

**Comment by yevgenypats** [comment]
Solved it but we should fix the autogeneration script to use only lowercase as otherwise it causes issues on various OSs and git (for example on mac if you change a filename to lowercase, git won't detect this change and you wont be able to commit that)

**Comment by bbernays** [comment]
fixed in #100
